name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore KintoneDiscordConnector/KintoneDiscordConnector.csproj

    - name: Build
      run: dotnet build KintoneDiscordConnector/KintoneDiscordConnector.csproj -c Release --no-restore

    - name: Publish
      run: dotnet publish KintoneDiscordConnector/KintoneDiscordConnector.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

    - name: Create ZIP archive
      run: Compress-Archive -Path ./publish/* -DestinationPath KintoneDiscordConnector-win-x64.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: KintoneDiscordConnector-win-x64
        path: KintoneDiscordConnector-win-x64.zip

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: KintoneDiscordConnector-win-x64.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
